# Generated by Django 4.1.4 on 2023-01-07 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_amount', models.PositiveIntegerField()),
                ('type', models.CharField(default='Classic', max_length=25)),
                ('is_finished', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='game.player')),
            ],
        ),
    ]
