# Generated by Django 4.1.4 on 2023-01-07 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_player_player_player_alter_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='game', to='game.player'),
            preserve_default=False,
        ),
    ]
