# Generated by Django 4.1.4 on 2023-01-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_player_player_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game', to='game.game'),
        ),
    ]
